{
  "name": "wa-webjs",
  "version": "0.1",
  "slug": "wa-webjs",
  "description": "wa-webjs",
  "ports": {
    "8998/tcp": 8998
  },
  "options": {
    "main_js": "/share/wa-webjs/main.js"
  },
  "schema": {
    "main_js": "str"
  },
  "map": ["share:rw"],
  "arch": ["amd64", "aarch64", "armv7"],
  "init": false
}
