{
  "name": "wa-automate",
  "version": "0.0.1",
  "slug": "wa-automate",
  "description": "wa-automate",
  "options": {
    "web_port": 8998,
    "nodejs_port": 8999,
    "main_js": "const wa = require('@open-wa/wa-automate');",
  },
  "schema": {
    "web_port": "port",
    "nodejs_port": "port",
    "main_js": "str",
  },
  "map": ["share:rw"]
}
