{
  "name": "wa-automate",
  "version": "0.0.1",
  "slug": "wa-automate",
  "description": "wa-automate",
  "options": {
    "web_port": 8998,
    "nodejs_port": 8999,
    "main_js": "/share/wa-automate/main.js"
  },
  "schema": {
    "web_port": "port",
    "nodejs_port": "port",
    "main_js": "str"
  },
  "map": ["share:rw"],
  "arch": ["amd64", "aarch64", "armv7"]
  "init": false
}
